/*
 * SkeletonProperties.h
 *
 *  Created on: 11 de Fev de 2013
 *      Author: fahrenheit
 */

#ifndef SKELETONPROPERTIES_H_
#define SKELETONPROPERTIES_H_

namespace Skeltrack {

enum SkeletonProperties {
    PROP_DIMENSION_REDUCTION,
    PROP_GRAPH_DISTANCE_THRESHOLD,
    PROP_GRAPH_MIN_NR_NODES,
    PROP_HANDS_MINIMUM_DISTANCE,
    PROP_SHOULDERS_CIRCUMFERENCE_RADIUS,
    PROP_SHOULDERS_ARC_START_POINT,
    PROP_SHOULDERS_ARC_LENGTH,
    PROP_SHOULDERS_SEARCH_STEP,
    PROP_EXTREMA_SPHERE_RADIUS,
    PROP_SMOOTHING_FACTOR,
    PROP_JOINTS_PERSISTENCY,
    PROP_ENABLE_SMOOTHING,
    PROP_TORSO_MINIMUM_NUMBER_NODES
};

}

#endif /* SKELETONPROPERTIES_H_ */
